[project]
name = "advanced-rag-chatbot"
version = "0.1.0"
description = "RAGBot"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.0.8",
    "langchain-anthropic>=1.1.0",
]

[project.scripts]
start = "advanced_rag_chatbot.main:main"
